name: build

on:
    pull_request:
        types: [closed]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged

        steps:
            - name: checkout
              if: github.event.pull_request.merged
              uses: actions/checkout@v1

            - name: Install dependencies
              run: yarn install --non-interactive

            - name: Make Production Build
              run: yarn run production

            - name: Commit production build
              uses: EndBug/add-and-commit@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
              with:
                  add: '.'

                  author_name: Production Bot
                  author_email: bot@aw-studio.de

                  message: 'Apply production build form CI'
